version: '3.7'

services:
  cpop_bot:
    build: .
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
